name: Tests

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: [ GC456 ]
  pull_request:
    branches: [ GC456 ]
  workflow_dispatch:

concurrency: 
  group: workflow
  cancel-in-progress: true


jobs:
  pipeline:
      
    runs-on: windows-2025-vs2026
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    
    timeout-minutes: 4320

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout AMMR
        uses: actions/checkout@v2
        with:
          repository: AnyBody/AMMR4-Beta
          path: ammr
          ref: ammr4-beta
      
      - name: Link AMMR
        shell: cmd
        run: |
          echo #include "%GITHUB_WORKSPACE%/ammr/libdef.any" > ammrlibdef.any
        
      - uses: prefix-dev/setup-pixi@v0.9.5
        with: 
          post-cleanup: false

      #- name: Run AMMR tests
      #  run: pixi run pytest

      #- name: Checkout AMMR
      #  run: |
      #    pixi run checkout-ammr
      - name: Run parameter identification (testing and preparation)
        run: |
          pixi run test-paramid
        env:
          RLM_LICENSE: ${{ secrets.LICENSE_SERVER }}
          RLM_LICENSE_PASSWORD: ${{ secrets.LICENSE_PASSWORD }}
      - name: Run tests
        run: |
          pixi run test-motion
        env:
          RLM_LICENSE: ${{ secrets.LICENSE_SERVER }}
          RLM_LICENSE_PASSWORD: ${{ secrets.LICENSE_PASSWORD }}        